/* autogenerated from ./opcodes_ddfd.dat, do not edit */

/*ADD IX,BC*/
static void op_DD_0x09(Z80EX_CONTEXT *cpu)
{
	ADD16(IX,BC);
	T_WAIT_UNTIL(15);
	return;
}

/*ADD IX,DE*/
static void op_DD_0x19(Z80EX_CONTEXT *cpu)
{
	ADD16(IX,DE);
	T_WAIT_UNTIL(15);
	return;
}

/*LD IX,nnnn*/
static void op_DD_0x21(Z80EX_CONTEXT *cpu)
{
	temp_word.b.l=READ_OP();
	temp_word.b.h=READ_OP();
	LD16(IX,temp_word.w);
	T_WAIT_UNTIL(14);
	return;
}

/*LD (nnnn),IX*/
static void op_DD_0x22(Z80EX_CONTEXT *cpu)
{
	temp_addr.b.l=READ_OP();
	temp_addr.b.h=READ_OP();
	LD16(temp_word.w,IX);
	WRITE_MEM(temp_addr.w,temp_word.b.l,14);
	WRITE_MEM(temp_addr.w+1,temp_word.b.h,17);
	T_WAIT_UNTIL(20);
	return;
}

/*INC IX*/
static void op_DD_0x23(Z80EX_CONTEXT *cpu)
{
	INC16(IX);
	T_WAIT_UNTIL(10);
	return;
}

/*INC IXH*/
static void op_DD_0x24(Z80EX_CONTEXT *cpu)
{
	INC(IXH);
	T_WAIT_UNTIL(9);
	return;
}

/*DEC IXH*/
static void op_DD_0x25(Z80EX_CONTEXT *cpu)
{
	DEC(IXH);
	T_WAIT_UNTIL(9);
	return;
}

/*LD IXH,nn*/
static void op_DD_0x26(Z80EX_CONTEXT *cpu)
{
	temp_byte=READ_OP();
	LD(IXH,temp_byte);
	T_WAIT_UNTIL(9);
	return;
}

/*ADD IX,IX*/
static void op_DD_0x29(Z80EX_CONTEXT *cpu)
{
	ADD16(IX,IX);
	T_WAIT_UNTIL(15);
	return;
}

/*LD IX,(nnnn)*/
static void op_DD_0x2a(Z80EX_CONTEXT *cpu)
{
	temp_addr.b.l=READ_OP();
	temp_addr.b.h=READ_OP();
	READ_MEM(temp_word.b.l,temp_addr.w,14);
	READ_MEM(temp_word.b.h,temp_addr.w+1,17);
	LD16(IX,temp_word.w);
	T_WAIT_UNTIL(20);
	return;
}

/*DEC IX*/
static void op_DD_0x2b(Z80EX_CONTEXT *cpu)
{
	DEC16(IX);
	T_WAIT_UNTIL(10);
	return;
}

/*INC IXL*/
static void op_DD_0x2c(Z80EX_CONTEXT *cpu)
{
	INC(IXL);
	T_WAIT_UNTIL(9);
	return;
}

/*DEC IXL*/
static void op_DD_0x2d(Z80EX_CONTEXT *cpu)
{
	DEC(IXL);
	T_WAIT_UNTIL(9);
	return;
}

/*LD IXL,nn*/
static void op_DD_0x2e(Z80EX_CONTEXT *cpu)
{
	temp_byte=READ_OP();
	LD(IXL,temp_byte);
	T_WAIT_UNTIL(9);
	return;
}

/*INC (IX+dd)*/
static void op_DD_0x34(Z80EX_CONTEXT *cpu)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	READ_MEM(temp_byte,IX+temp_byte_s,16);
	INC(temp_byte);
	WRITE_MEM(IX+temp_byte_s,temp_byte,20);
	T_WAIT_UNTIL(23);
	return;
}

/*DEC (IX+dd)*/
static void op_DD_0x35(Z80EX_CONTEXT *cpu)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	READ_MEM(temp_byte,IX+temp_byte_s,16);
	DEC(temp_byte);
	WRITE_MEM(IX+temp_byte_s,temp_byte,20);
	T_WAIT_UNTIL(23);
	return;
}

/*LD (IX+dd),nn*/
static void op_DD_0x36(Z80EX_CONTEXT *cpu)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	temp_byte=READ_OP();
	LD(temp_byte,temp_byte);
	WRITE_MEM(IX+temp_byte_s,temp_byte,16);
	T_WAIT_UNTIL(19);
	return;
}

/*ADD IX,SP*/
static void op_DD_0x39(Z80EX_CONTEXT *cpu)
{
	ADD16(IX,SP);
	T_WAIT_UNTIL(15);
	return;
}

/*LD B,IXH*/
static void op_DD_0x44(Z80EX_CONTEXT *cpu)
{
	LD(B,IXH);
	T_WAIT_UNTIL(9);
	return;
}

/*LD B,IXL*/
static void op_DD_0x45(Z80EX_CONTEXT *cpu)
{
	LD(B,IXL);
	T_WAIT_UNTIL(9);
	return;
}

/*LD B,(IX+dd)*/
static void op_DD_0x46(Z80EX_CONTEXT *cpu)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	READ_MEM(temp_byte,IX+temp_byte_s,16);
	LD(B,temp_byte);
	T_WAIT_UNTIL(19);
	return;
}

/*LD C,IXH*/
static void op_DD_0x4c(Z80EX_CONTEXT *cpu)
{
	LD(C,IXH);
	T_WAIT_UNTIL(9);
	return;
}

/*LD C,IXL*/
static void op_DD_0x4d(Z80EX_CONTEXT *cpu)
{
	LD(C,IXL);
	T_WAIT_UNTIL(9);
	return;
}

/*LD C,(IX+dd)*/
static void op_DD_0x4e(Z80EX_CONTEXT *cpu)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	READ_MEM(temp_byte,IX+temp_byte_s,16);
	LD(C,temp_byte);
	T_WAIT_UNTIL(19);
	return;
}

/*LD D,IXH*/
static void op_DD_0x54(Z80EX_CONTEXT *cpu)
{
	LD(D,IXH);
	T_WAIT_UNTIL(9);
	return;
}

/*LD D,IXL*/
static void op_DD_0x55(Z80EX_CONTEXT *cpu)
{
	LD(D,IXL);
	T_WAIT_UNTIL(9);
	return;
}

/*LD D,(IX+dd)*/
static void op_DD_0x56(Z80EX_CONTEXT *cpu)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	READ_MEM(temp_byte,IX+temp_byte_s,16);
	LD(D,temp_byte);
	T_WAIT_UNTIL(19);
	return;
}

/*LD E,IXH*/
static void op_DD_0x5c(Z80EX_CONTEXT *cpu)
{
	LD(E,IXH);
	T_WAIT_UNTIL(9);
	return;
}

/*LD E,IXL*/
static void op_DD_0x5d(Z80EX_CONTEXT *cpu)
{
	LD(E,IXL);
	T_WAIT_UNTIL(9);
	return;
}

/*LD E,(IX+dd)*/
static void op_DD_0x5e(Z80EX_CONTEXT *cpu)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	READ_MEM(temp_byte,IX+temp_byte_s,16);
	LD(E,temp_byte);
	T_WAIT_UNTIL(19);
	return;
}

/*LD IXH,B*/
static void op_DD_0x60(Z80EX_CONTEXT *cpu)
{
	LD(IXH,B);
	T_WAIT_UNTIL(9);
	return;
}

/*LD IXH,C*/
static void op_DD_0x61(Z80EX_CONTEXT *cpu)
{
	LD(IXH,C);
	T_WAIT_UNTIL(9);
	return;
}

/*LD IXH,D*/
static void op_DD_0x62(Z80EX_CONTEXT *cpu)
{
	LD(IXH,D);
	T_WAIT_UNTIL(9);
	return;
}

/*LD IXH,E*/
static void op_DD_0x63(Z80EX_CONTEXT *cpu)
{
	LD(IXH,E);
	T_WAIT_UNTIL(9);
	return;
}

/*LD IXH,IXH*/
static void op_DD_0x64(Z80EX_CONTEXT *cpu)
{
	LD(IXH,IXH);
	T_WAIT_UNTIL(9);
	return;
}

/*LD IXH,IXL*/
static void op_DD_0x65(Z80EX_CONTEXT *cpu)
{
	LD(IXH,IXL);
	T_WAIT_UNTIL(9);
	return;
}

/*LD H,(IX+dd)*/
static void op_DD_0x66(Z80EX_CONTEXT *cpu)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	READ_MEM(temp_byte,IX+temp_byte_s,16);
	LD(H,temp_byte);
	T_WAIT_UNTIL(19);
	return;
}

/*LD IXH,A*/
static void op_DD_0x67(Z80EX_CONTEXT *cpu)
{
	LD(IXH,A);
	T_WAIT_UNTIL(9);
	return;
}

/*LD IXL,B*/
static void op_DD_0x68(Z80EX_CONTEXT *cpu)
{
	LD(IXL,B);
	T_WAIT_UNTIL(9);
	return;
}

/*LD IXL,C*/
static void op_DD_0x69(Z80EX_CONTEXT *cpu)
{
	LD(IXL,C);
	T_WAIT_UNTIL(9);
	return;
}

/*LD IXL,D*/
static void op_DD_0x6a(Z80EX_CONTEXT *cpu)
{
	LD(IXL,D);
	T_WAIT_UNTIL(9);
	return;
}

/*LD IXL,E*/
static void op_DD_0x6b(Z80EX_CONTEXT *cpu)
{
	LD(IXL,E);
	T_WAIT_UNTIL(9);
	return;
}

/*LD IXL,IXH*/
static void op_DD_0x6c(Z80EX_CONTEXT *cpu)
{
	LD(IXL,IXH);
	T_WAIT_UNTIL(9);
	return;
}

/*LD IXL,IXL*/
static void op_DD_0x6d(Z80EX_CONTEXT *cpu)
{
	LD(IXL,IXL);
	T_WAIT_UNTIL(9);
	return;
}

/*LD L,(IX+dd)*/
static void op_DD_0x6e(Z80EX_CONTEXT *cpu)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	READ_MEM(temp_byte,IX+temp_byte_s,16);
	LD(L,temp_byte);
	T_WAIT_UNTIL(19);
	return;
}

/*LD IXL,A*/
static void op_DD_0x6f(Z80EX_CONTEXT *cpu)
{
	LD(IXL,A);
	T_WAIT_UNTIL(9);
	return;
}

/*LD (IX+dd),B*/
static void op_DD_0x70(Z80EX_CONTEXT *cpu)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	LD(temp_byte,B);
	WRITE_MEM(IX+temp_byte_s,temp_byte,16);
	T_WAIT_UNTIL(19);
	return;
}

/*LD (IX+dd),C*/
static void op_DD_0x71(Z80EX_CONTEXT *cpu)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	LD(temp_byte,C);
	WRITE_MEM(IX+temp_byte_s,temp_byte,16);
	T_WAIT_UNTIL(19);
	return;
}

/*LD (IX+dd),D*/
static void op_DD_0x72(Z80EX_CONTEXT *cpu)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	LD(temp_byte,D);
	WRITE_MEM(IX+temp_byte_s,temp_byte,16);
	T_WAIT_UNTIL(19);
	return;
}

/*LD (IX+dd),E*/
static void op_DD_0x73(Z80EX_CONTEXT *cpu)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	LD(temp_byte,E);
	WRITE_MEM(IX+temp_byte_s,temp_byte,16);
	T_WAIT_UNTIL(19);
	return;
}

/*LD (IX+dd),H*/
static void op_DD_0x74(Z80EX_CONTEXT *cpu)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	LD(temp_byte,H);
	WRITE_MEM(IX+temp_byte_s,temp_byte,16);
	T_WAIT_UNTIL(19);
	return;
}

/*LD (IX+dd),L*/
static void op_DD_0x75(Z80EX_CONTEXT *cpu)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	LD(temp_byte,L);
	WRITE_MEM(IX+temp_byte_s,temp_byte,16);
	T_WAIT_UNTIL(19);
	return;
}

/*LD (IX+dd),A*/
static void op_DD_0x77(Z80EX_CONTEXT *cpu)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	LD(temp_byte,A);
	WRITE_MEM(IX+temp_byte_s,temp_byte,16);
	T_WAIT_UNTIL(19);
	return;
}

/*LD A,IXH*/
static void op_DD_0x7c(Z80EX_CONTEXT *cpu)
{
	LD(A,IXH);
	T_WAIT_UNTIL(9);
	return;
}

/*LD A,IXL*/
static void op_DD_0x7d(Z80EX_CONTEXT *cpu)
{
	LD(A,IXL);
	T_WAIT_UNTIL(9);
	return;
}

/*LD A,(IX+dd)*/
static void op_DD_0x7e(Z80EX_CONTEXT *cpu)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	READ_MEM(temp_byte,IX+temp_byte_s,16);
	LD(A,temp_byte);
	T_WAIT_UNTIL(19);
	return;
}

/*ADD A,IXH*/
static void op_DD_0x84(Z80EX_CONTEXT *cpu)
{
	ADD(A,IXH);
	T_WAIT_UNTIL(9);
	return;
}

/*ADD A,IXL*/
static void op_DD_0x85(Z80EX_CONTEXT *cpu)
{
	ADD(A,IXL);
	T_WAIT_UNTIL(9);
	return;
}

/*ADD A,(IX+dd)*/
static void op_DD_0x86(Z80EX_CONTEXT *cpu)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	READ_MEM(temp_byte,IX+temp_byte_s,16);
	ADD(A,temp_byte);
	T_WAIT_UNTIL(19);
	return;
}

/*ADC A,IXH*/
static void op_DD_0x8c(Z80EX_CONTEXT *cpu)
{
	ADC(A,IXH);
	T_WAIT_UNTIL(9);
	return;
}

/*ADC A,IXL*/
static void op_DD_0x8d(Z80EX_CONTEXT *cpu)
{
	ADC(A,IXL);
	T_WAIT_UNTIL(9);
	return;
}

/*ADC A,(IX+dd)*/
static void op_DD_0x8e(Z80EX_CONTEXT *cpu)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	READ_MEM(temp_byte,IX+temp_byte_s,16);
	ADC(A,temp_byte);
	T_WAIT_UNTIL(19);
	return;
}

/*SUB IXH*/
static void op_DD_0x94(Z80EX_CONTEXT *cpu)
{
	SUB(IXH);
	T_WAIT_UNTIL(9);
	return;
}

/*SUB IXL*/
static void op_DD_0x95(Z80EX_CONTEXT *cpu)
{
	SUB(IXL);
	T_WAIT_UNTIL(9);
	return;
}

/*SUB (IX+dd)*/
static void op_DD_0x96(Z80EX_CONTEXT *cpu)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	READ_MEM(temp_byte,IX+temp_byte_s,16);
	SUB(temp_byte);
	T_WAIT_UNTIL(19);
	return;
}

/*SBC A,IXH*/
static void op_DD_0x9c(Z80EX_CONTEXT *cpu)
{
	SBC(A,IXH);
	T_WAIT_UNTIL(9);
	return;
}

/*SBC A,IXL*/
static void op_DD_0x9d(Z80EX_CONTEXT *cpu)
{
	SBC(A,IXL);
	T_WAIT_UNTIL(9);
	return;
}

/*SBC A,(IX+dd)*/
static void op_DD_0x9e(Z80EX_CONTEXT *cpu)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	READ_MEM(temp_byte,IX+temp_byte_s,16);
	SBC(A,temp_byte);
	T_WAIT_UNTIL(19);
	return;
}

/*AND IXH*/
static void op_DD_0xa4(Z80EX_CONTEXT *cpu)
{
	AND(IXH);
	T_WAIT_UNTIL(9);
	return;
}

/*AND IXL*/
static void op_DD_0xa5(Z80EX_CONTEXT *cpu)
{
	AND(IXL);
	T_WAIT_UNTIL(9);
	return;
}

/*AND (IX+dd)*/
static void op_DD_0xa6(Z80EX_CONTEXT *cpu)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	READ_MEM(temp_byte,IX+temp_byte_s,16);
	AND(temp_byte);
	T_WAIT_UNTIL(19);
	return;
}

/*XOR IXH*/
static void op_DD_0xac(Z80EX_CONTEXT *cpu)
{
	XOR(IXH);
	T_WAIT_UNTIL(9);
	return;
}

/*XOR IXL*/
static void op_DD_0xad(Z80EX_CONTEXT *cpu)
{
	XOR(IXL);
	T_WAIT_UNTIL(9);
	return;
}

/*XOR (IX+dd)*/
static void op_DD_0xae(Z80EX_CONTEXT *cpu)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	READ_MEM(temp_byte,IX+temp_byte_s,16);
	XOR(temp_byte);
	T_WAIT_UNTIL(19);
	return;
}

/*OR IXH*/
static void op_DD_0xb4(Z80EX_CONTEXT *cpu)
{
	OR(IXH);
	T_WAIT_UNTIL(9);
	return;
}

/*OR IXL*/
static void op_DD_0xb5(Z80EX_CONTEXT *cpu)
{
	OR(IXL);
	T_WAIT_UNTIL(9);
	return;
}

/*OR (IX+dd)*/
static void op_DD_0xb6(Z80EX_CONTEXT *cpu)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	READ_MEM(temp_byte,IX+temp_byte_s,16);
	OR(temp_byte);
	T_WAIT_UNTIL(19);
	return;
}

/*CP IXH*/
static void op_DD_0xbc(Z80EX_CONTEXT *cpu)
{
	CP(IXH);
	T_WAIT_UNTIL(9);
	return;
}

/*CP IXL*/
static void op_DD_0xbd(Z80EX_CONTEXT *cpu)
{
	CP(IXL);
	T_WAIT_UNTIL(9);
	return;
}

/*CP (IX+dd)*/
static void op_DD_0xbe(Z80EX_CONTEXT *cpu)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	READ_MEM(temp_byte,IX+temp_byte_s,16);
	CP(temp_byte);
	T_WAIT_UNTIL(19);
	return;
}



/*POP IX*/
static void op_DD_0xe1(Z80EX_CONTEXT *cpu)
{
	POP(IX, /*rd*/8,11);
	T_WAIT_UNTIL(14);
	return;
}

/*EX (SP),IX*/
static void op_DD_0xe3(Z80EX_CONTEXT *cpu)
{
	READ_MEM(temp_word.b.l,SP,8);
	READ_MEM(temp_word.b.h,SP+1,11);
	EX(temp_word.w,IX);
	WRITE_MEM(SP,temp_word.b.l,15);
	WRITE_MEM(SP+1,temp_word.b.h,18);
	T_WAIT_UNTIL(23);
	return;
}

/*PUSH IX*/
static void op_DD_0xe5(Z80EX_CONTEXT *cpu)
{
	PUSH(IX, /*wr*/9,12);
	T_WAIT_UNTIL(15);
	return;
}

/*JP IX*/
static void op_DD_0xe9(Z80EX_CONTEXT *cpu)
{
	JP(IX);
	T_WAIT_UNTIL(8);
	return;
}

/*LD SP,IX*/
static void op_DD_0xf9(Z80EX_CONTEXT *cpu)
{
	LD16(SP,IX);
	T_WAIT_UNTIL(10);
	return;
}



/**/
static z80ex_opcode_fn opcodes_dd[0x100] = {
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , op_DD_0x09    , NULL          , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , op_DD_0x19    , NULL          , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , op_DD_0x21    , op_DD_0x22    , op_DD_0x23    ,
 op_DD_0x24    , op_DD_0x25    , op_DD_0x26    , NULL          ,
 NULL          , op_DD_0x29    , op_DD_0x2a    , op_DD_0x2b    ,
 op_DD_0x2c    , op_DD_0x2d    , op_DD_0x2e    , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 op_DD_0x34    , op_DD_0x35    , op_DD_0x36    , NULL          ,
 NULL          , op_DD_0x39    , NULL          , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 op_DD_0x44    , op_DD_0x45    , op_DD_0x46    , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 op_DD_0x4c    , op_DD_0x4d    , op_DD_0x4e    , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 op_DD_0x54    , op_DD_0x55    , op_DD_0x56    , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 op_DD_0x5c    , op_DD_0x5d    , op_DD_0x5e    , NULL          ,
 op_DD_0x60    , op_DD_0x61    , op_DD_0x62    , op_DD_0x63    ,
 op_DD_0x64    , op_DD_0x65    , op_DD_0x66    , op_DD_0x67    ,
 op_DD_0x68    , op_DD_0x69    , op_DD_0x6a    , op_DD_0x6b    ,
 op_DD_0x6c    , op_DD_0x6d    , op_DD_0x6e    , op_DD_0x6f    ,
 op_DD_0x70    , op_DD_0x71    , op_DD_0x72    , op_DD_0x73    ,
 op_DD_0x74    , op_DD_0x75    , NULL          , op_DD_0x77    ,
 NULL          , NULL          , NULL          , NULL          ,
 op_DD_0x7c    , op_DD_0x7d    , op_DD_0x7e    , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 op_DD_0x84    , op_DD_0x85    , op_DD_0x86    , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 op_DD_0x8c    , op_DD_0x8d    , op_DD_0x8e    , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 op_DD_0x94    , op_DD_0x95    , op_DD_0x96    , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 op_DD_0x9c    , op_DD_0x9d    , op_DD_0x9e    , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 op_DD_0xa4    , op_DD_0xa5    , op_DD_0xa6    , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 op_DD_0xac    , op_DD_0xad    , op_DD_0xae    , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 op_DD_0xb4    , op_DD_0xb5    , op_DD_0xb6    , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 op_DD_0xbc    , op_DD_0xbd    , op_DD_0xbe    , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , NULL          , NULL          , opc_DDCB      ,
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , op_DD_0xe1    , NULL          , op_DD_0xe3    ,
 NULL          , op_DD_0xe5    , NULL          , NULL          ,
 NULL          , op_DD_0xe9    , NULL          , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , op_DD_0xf9    , NULL          , NULL          ,
 NULL          , NULL          , NULL          , NULL          
};
